### ISSUE TITLE
Failed to use sonarqube-repair as dependency

### ISSUE THREAD

**Issue by henry-lp** [SpoonLabs/sonarqube-repair#103] opened 2020-05-05 13:17 UTC
This was run in Repairnator after importing in the `pom.xml` .

```
mons.ProgressReport - 0/0 source files have been analyzed 
java.lang.NullPointerException
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.scanFiles(MultipleFilesJavaCheckVerifier.java:116)
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.verify(MultipleFilesJavaCheckVerifier.java:91)
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.verify(MultipleFilesJavaCheckVerifier.java:58)
	at sonarquberepair.processor.SQRAbstractProcessor.<init>(SQRAbstractProcessor.java:39)
	at sonarquberepair.processor.ArrayHashCodeAndToStringProcessor.<init>(ArrayHashCodeAndToStringProcessor.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sonarquberepair.DefaultRepair.repair(DefaultRepair.java:51)
	at sonarquberepair.Main.start(Main.java:84)
	at sonarquberepair.Main.main(Main.java:90)
	at fr.inria.spirals.repairnator.process.step.repair.SonarQubeRepair.businessExecute(SonarQubeRepair.java:48)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:336)
	at fr.inria.spirals.repairnator.process.step.repair.AbstractRepairStep.execute(AbstractRepairStep.java:60)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:188)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:353)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:188)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:353)
	at fr.inria.spirals.repairnator.process.inspectors.components.RunInspector4DefaultGit.run(RunInspector4DefaultGit.java:109)
	at fr.inria.spirals.repairnator.process.inspectors.ProjectInspector.run(ProjectInspector.java:301)
	at fr.inria.spirals.repairnator.pipeline.GithubMainProcess.run(GithubMainProcess.java:126)
	at fr.inria.spirals.repairnator.pipeline.BranchLauncher.main(BranchLauncher.java:97)
	at fr.inria.spirals.repairnator.pipeline.BranchLauncher.launch(BranchLauncher.java:103)
	at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:67)
done
```

Apparently the local changes are not there, which explain why we still get null (bug in the front end). 
:)

**Comment by fermadeiral** [comment] 2020-05-05 13:25
@henry-lp, I know nothing about the problem. Please, give way more information.

**Comment by henry-lp** [comment] 2020-05-05 13:45
@fermadeiral , I understand :) . 

`org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.scanFiles(MultipleFilesJavaCheckVerifier.java:116)` indicates that when you scanFiles to get a list of objects . It returned null , which should be fixed by your changes in `VisitorBridge4Tests` class , I think :) .

**Comment by fermadeiral** [comment] 2020-05-05 13:56
Let's put this way: I have no idea on what you are doing (see, I understand the stack trace, but I don't know what you did to get there).

Thus to start:

1) What is the jar file you are using?
2) How are you calling it?

For the future, always give a context for the problem you are facing, in this repository and in any other repository.

**Comment by henry-lp** [comment] 2020-05-05 15:32
My apologies, I'll be clearer next time :) . 

I am not calling any Jar directly, but imported your newly deployed sonarqube-version with maven then run the repair in Repairnator.

**Comment by fermadeiral** [comment] 2020-05-05 18:19
Ok, now I understand a little more.

Did you try to use the jar with dependencies in your pom.xml?

**Comment by henry-lp** [comment] 2020-05-05 18:40
I just included the dependency like this 
```
<dependency>
  <groupId>se.kth.castor</groupId>
  <artifactId>sonarqube-repair</artifactId>
  <version>1.1-SNAPSHOT</version>
  <classifier>jar-with-dependencies</classifier>
</dependency>
```
and it gives the same output as above .

**Comment by fermadeiral** [comment] 2020-05-06 10:54
I cannot reproduce the bug because when I do `mvn package -DskipTests` as you said I got several compilation errors before having a jar from repairnator to run.

I will try something else here and then I will tell you.

**Comment by fermadeiral** [comment] 2020-05-07 08:40
@henry-lp, I deployed this morning a new snapshot of sonarqube-repair containing the change of yesterday night: https://oss.sonatype.org/content/repositories/snapshots/se/kth/castor/sonarqube-repair/

Please, try the integration with Repairnator again with this new snapshot. If it works, we can close this issue.

**Comment by henry-lp** [comment] 2020-05-07 09:24
@fermadeiral thanks , Fernanda. I tried and it work locally. Wait for CI at Repairnator to pass as well then this issue will be closed.

**Closed** 2020-05-14 19:12 UTC
